#!/usr/bin/perl
use strict;
use warnings;

######################################################
## You can append this script to your personal code ##
######################################################

##NOTE: This code cannot run on its own

##Correcting Length of Shorter File
	#variables @TCmatches and @CCmatches can be changed to match personal code
	#CC Matches = methylated regions
	#TC Matches = unmethylated regions

if(scalar@TCmatches<scalar@CCmatches){		
	print "TCmatches is shorter than CCmatches\n\n";
	do{	my$m=scalar @TCmatches;
		$TCmatches[$m]="NA";		#R ignores NA when graphing and computing
		}while(scalar@TCmatches<scalar@CCmatches);
	print "@TCmatches\n\n";
	print "@CCmatches\n\n";
	}
	
if(scalar @CCmatches<scalar@TCmatches){
	print "TCmatches is longer than CCmatches\n\n";
	do{	my$m=scalar @CCmatches;
		$CCmatches[$m]="NA";
		}while(scalar@CCmatches<scalar@TCmatches);
	print @CCmatches;
	}

##############################
## Export Data as Two Files ##
##############################

##You can change the @CCmatches and @TCmatches variables to match the array variables that you want to export
##Export Files will be placed in the working directory

my $outputfile = 'MethylatedReport.txt';	#leave variables unchanged
open(my $fh, '>', $outputfile) || die "Could not open file '$outputfile'";
print $fh "@CCmatches\n\n";
close $fh;

my $outputfile2 = 'UnmethylatedReport.txt';
open($fh, '>', $outputfile2) || die "Could not open file '$outputfile2'";
print $fh "@TCmatches\n\n";
close $fh;

## These files will be used by an R Code to graph CG regions
## One File should contain methylated CG regions (CCmatch), the other should contain unmethylated CG regions (TCmatch)




exit;
